# Generated by Django 6.1.1 on 2026-09-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor primeiro).')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Projecto',
                'verbose_name_plural': 'Categorias de Projectos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor primeiro).')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='Cliente (opcional)')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Localização')),
                ('results', models.TextField(blank=True, verbose_name='Resultados')),
                ('status', models.CharField(choices=[('PUBLISHED', 'Publicado'), ('DRAFT', 'Rascunho')], default='DRAFT', max_length=20)),
                ('services_involved', models.ManyToManyField(blank=True, related_name='projects', to='catalog.service', verbose_name='Serviços envolvidos')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'verbose_name': 'Projecto',
                'verbose_name_plural': 'Projectos',
                'ordering': ['order', '-date'],
            },
        ),
    ]
