# Generated by Django 6.1.1 on 2026-09-07 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('procurement', '0001_initial'),
        ('software', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('request_type', models.CharField(choices=[('SERVICE', 'Serviço'), ('SOFTWARE', 'Software'), ('SUPPLY', 'Fornecimento'), ('CONSULTING', 'Consultoria'), ('OTHER', 'Outro')], max_length=20)),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('description', models.TextField(verbose_name='Descrição da necessidade')),
                ('quantity', models.CharField(blank=True, max_length=50, verbose_name='Quantidade')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Orçamento estimado')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Localização')),
                ('deadline', models.CharField(blank=True, max_length=100, verbose_name='Prazo')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='quote_attachments/%Y/%m/')),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('UNDER_REVIEW', 'Em análise'), ('CONTACTED', 'Cliente contactado'), ('QUOTATION_PREPARED', 'Proposta preparada'), ('AWAITING_APPROVAL', 'Aguarda aprovação'), ('APPROVED', 'Aprovado'), ('PROCUREMENT', 'Em aquisição'), ('FULFILLED', 'Fornecido'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='NEW', max_length=25)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta')], default='NORMAL', max_length=10)),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('privacy_consent', models.BooleanField(default=False, verbose_name='Consentimento de privacidade')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='procurement.productcategory')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='catalog.service')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='software.softwaresolution')),
            ],
            options={
                'verbose_name': 'Pedido de Orçamento',
                'verbose_name_plural': 'Pedidos de Orçamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_order_number', models.CharField(blank=True, max_length=60, verbose_name='N.º Ordem de Saque')),
                ('withdrawal_order_date', models.DateField(blank=True, null=True, verbose_name='Data da Ordem de Saque')),
                ('withdrawal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montante (Kz)')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor')),
                ('procurement_notes', models.TextField(blank=True, verbose_name='Notas de aquisição')),
                ('procurement_status', models.CharField(choices=[('NOT_REQUIRED', 'Não aplicável'), ('PENDING', 'Pendente'), ('ISSUED', 'Emitida'), ('USED', 'Utilizada'), ('CANCELLED', 'Cancelada')], default='NOT_REQUIRED', max_length=20)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_detail', to='quotes.quoterequest')),
            ],
            options={
                'verbose_name': 'Detalhe de Aquisição (Ordem de Saque)',
                'verbose_name_plural': 'Detalhes de Aquisição (Ordens de Saque)',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=25)),
                ('new_status', models.CharField(max_length=25)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quotes.quoterequest')),
            ],
            options={
                'verbose_name': 'Histórico de Pedido',
                'verbose_name_plural': 'Histórico de Pedidos',
                'ordering': ['created_at'],
            },
        ),
    ]
