# Generated by Django 6.1.1 on 2026-09-07 20:54

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='quote_attachments/%Y/%m/', validators=[apps.core.validators.validate_upload_file]),
        ),
    ]
