# Generated by Django 6.1.1 on 2026-09-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quoterequest_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='request_type',
            field=models.CharField(choices=[('SERVICE', 'Serviço'), ('SOFTWARE', 'Software'), ('SUPPLY', 'Fornecimento'), ('CONSULTING', 'Consultoria'), ('DEMO', 'Demonstração'), ('PROPOSAL', 'Proposta'), ('OTHER', 'Outro')], max_length=20),
        ),
    ]
