# Generated by Django 6.1.1 on 2026-09-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor primeiro).')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('AVAILABLE_ON_REQUEST', 'Disponível sob consulta'), ('DEVELOPMENT', 'Em desenvolvimento'), ('INACTIVE', 'Inactiva')], default='AVAILABLE_ON_REQUEST', max_length=25)),
            ],
            options={
                'verbose_name': 'Área de Actividade',
                'verbose_name_plural': 'Áreas de Actividade',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor primeiro).')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor primeiro).')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=300, verbose_name='Descrição curta')),
                ('full_description', models.TextField(verbose_name='Descrição completa')),
                ('benefits', models.TextField(blank=True, help_text='Um benefício por linha.', verbose_name='Benefícios')),
                ('process', models.TextField(blank=True, help_text='Um passo por linha.', verbose_name='Processo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('cta_label', models.CharField(default='Solicitar orçamento', max_length=80, verbose_name='Texto do CTA')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order', 'name'],
            },
        ),
    ]
