# Generated by Django 6.1.1 on 2026-09-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessarea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_areas/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='businessarea',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('AVAILABLE_ON_REQUEST', 'Sob solicitação'), ('CONSULTATION', 'Sob consulta'), ('DEVELOPMENT', 'Em desenvolvimento'), ('INACTIVE', 'Inactiva')], default='AVAILABLE_ON_REQUEST', max_length=25),
        ),
    ]
