# Generated by Django 6.1.1 on 2026-09-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(default='ARSMART - COMÉRCIO GERAL E PRESTAÇÃO DE SERVIÇOS (SU), LDA', max_length=255, verbose_name='Firma (nome legal)')),
                ('trade_name', models.CharField(default='ARSMART', max_length=100, verbose_name='Nome comercial')),
                ('nif', models.CharField(default='5002476959', max_length=30, verbose_name='NIF')),
                ('registration_number', models.CharField(default='13222-25/250420', max_length=60, verbose_name='Matrícula')),
                ('legal_form', models.CharField(default='Sociedade Unipessoal por Quotas', max_length=120, verbose_name='Forma jurídica')),
                ('founded_year', models.PositiveIntegerField(default=2025, verbose_name='Ano de constituição')),
                ('capital', models.DecimalField(decimal_places=2, default=100000.0, max_digits=14, verbose_name='Capital social (Kz)')),
                ('address', models.TextField(default='Bairro Centro Urbano, Rua Principal do Centro Urbano, casa s/n.º, nas imediações da ENDE-Dundo e Largo Samanhoga', verbose_name='Morada')),
                ('province', models.CharField(default='Lunda Norte', max_length=120, verbose_name='Província')),
                ('municipality', models.CharField(default='Dundo', max_length=120, verbose_name='Município')),
                ('country', models.CharField(default='Angola', max_length=120, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(blank=True, help_text='Formato internacional, ex: 244900000000', max_length=30, verbose_name='WhatsApp')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, default='A ARSMART ajuda empresas, instituições e clientes a resolver necessidades através de serviços, soluções tecnológicas, software, consultoria e fornecimento sob solicitação.', verbose_name='Descrição institucional')),
                ('mission', models.TextField(blank=True, verbose_name='Missão')),
                ('vision', models.TextField(blank=True, verbose_name='Visão')),
                ('values', models.TextField(blank=True, help_text='Um valor por linha.', verbose_name='Valores')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logótipo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Favicon')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Localização (Google Maps)')),
            ],
            options={
                'verbose_name': 'Perfil da Empresa',
                'verbose_name_plural': 'Perfil da Empresa',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Resposta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Definição do Site',
                'verbose_name_plural': 'Definições do Site',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('TIKTOK', 'TikTok'), ('YOUTUBE', 'YouTube'), ('X', 'X (Twitter)')], max_length=20)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['order'],
            },
        ),
    ]
