# Generated by Django 6.1.1 on 2026-09-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor primeiro).')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('developer', models.CharField(blank=True, max_length=150, verbose_name='Fabricante/Desenvolvedor')),
                ('category', models.CharField(blank=True, max_length=150, verbose_name='Categoria')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descrição curta')),
                ('full_description', models.TextField(verbose_name='Descrição completa')),
                ('features', models.TextField(blank=True, help_text='Uma por linha.', verbose_name='Funcionalidades')),
                ('benefits', models.TextField(blank=True, help_text='Um por linha.', verbose_name='Benefícios')),
                ('target_audience', models.TextField(blank=True, verbose_name='Público-alvo')),
                ('requirements', models.TextField(blank=True, verbose_name='Requisitos')),
                ('license_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscrição'), ('PERPETUAL', 'Licença perpétua'), ('QUOTE_ONLY', 'Sob consulta')], default='QUOTE_ONLY', max_length=20)),
                ('price_note', models.CharField(blank=True, max_length=150, verbose_name='Nota de preço (opcional)')),
                ('documentation_url', models.URLField(blank=True, verbose_name='Documentação')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='software/')),
            ],
            options={
                'verbose_name': 'Solução de Software',
                'verbose_name_plural': 'Soluções de Software',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='software/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='software.softwaresolution')),
            ],
            options={
                'verbose_name': 'Screenshot de Software',
                'verbose_name_plural': 'Screenshots de Software',
                'ordering': ['order'],
            },
        ),
    ]
