# Generated by Django 6.1.1 on 2026-09-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaresolution',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Vídeo (URL)'),
        ),
    ]
